### PR TITLE
Some enhancements (e.g. execute/put/get)

### PR DESCRIPTION
**Pull request by keesbos**
* Implemented of container_execute
* Releave pin to pip_version 2.0.5
* Implemented container_file_get
* Implemented container_file_put
* Implemented container_state

### CODE REVIEW

**Comment by jochumdev** [comment]
WOW, great one. I'll test it these evening then merge.

**Comment by jochumdev** [comment]
Please also adjust the README (remove the todos).

**Comment by keesbos** [comment]
Did update the todo. Note that I've worked on the module and not on the states. So, the put/get and probably the execute still need to be addressed in `lxd_container.py`

**Comment by jochumdev** [comment]
Tested, works fine.

**Comment by jochumdev** [comment]
This formula is now official, further development happens at: https://github.com/saltstack-formulas/lxd-formula

**Pull request merged**
