### PR TITLE
Some changes (enhancements/bugfixes)

### PR DESCRIPTION
**Pull request by keesbos**
* Start support new api pylxd
* Consistent lxd module check
* Default saltenv is current (active) __env__
* Fix for alias setting on images

### CODE REVIEW

**Comment by jochumdev** [comment]
WOW nice, the first PR on this one.

I want the execution module and the execution states in salt/develop but never got the time to do what you already did.

Is this ready to merge (and possible get run) ?

Please add yourself to the README as Author, You accept the Apache 2.0 License, right?

**Comment by jochumdev** [comment]
About the upgrade of PyLXD, I thought we could entirely remove the "Image" import and see
if the incoming value is not str then its an image.

**Comment by jochumdev** [comment]
Ok, going to merge that. Thanks!

**Comment by keesbos** [comment]
This should be runnable for pylxd 2.0.5. and 2.2.2. Changes should be backwards compatible.

I've added myself as author (company email address). We love the Apache 2.0 license (and of course accept it).

Currently, I have to use `'remote_addr': 'http+unix://%2Fvar%2Flib%2Flxd%2Funix.socket',` to work around a bug in pylxd ( https://github.com/lxc/pylxd/pull/212 ). Which could be worked around in the formula too (use remote_addr = None when it's `'/var/lib/lxd/unix.socket'`, since it's the default value in pylxd and then it works).

The import of `Image` can be omitted. We can check if `image` is a string, otherwise it should have the attribute `fingerprint`. If not, we have something else (or an invalid image?).

**Comment by jochumdev** [comment]
Please make a extra PR for that work around, I'll merge it, can you also omit the import?

Do you have the time to implement exec and file push/pull ?

Forgot something: Its nice code you make.

**Pull request merged**
